name: fintech
channels:
  - conda-forge
dependencies:
  - archspec=0.2.5
  - boltons=24.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - colorama=0.4.6
  - conda=24.11.3
  - conda-libmamba-solver=24.9.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - distro=1.9.0
  - fmt=11.0.2
  - frozendict=2.4.6
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - krb5=1.21.3
  - libarchive=3.7.7
  - libcurl=8.11.1
  - libexpat=2.6.4
  - libffi=3.4.2
  - libiconv=1.17
  - liblzma=5.6.3
  - libmamba=1.5.12
  - libmambapy=1.5.12
  - libsolv=0.7.30
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libxml2=2.13.5
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - mamba=1.5.12
  - openssl=3.4.0
  - packaging=24.2
  - pip=24.3.1
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.12.8
  - python_abi=3.12
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.3
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.8
  - setuptools=75.8.0
  - tk=8.6.13
  - tqdm=4.67.1
  - truststore=0.10.0
  - tzdata=2025a
  - wheel=0.45.1
  - yaml-cpp=0.8.0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - contourpy==1.3.1
      - cycler==0.12.1
      - fonttools==4.56.0
      - kiwisolver==1.4.8
      - koreanize-matplotlib==0.1.1
      - matplotlib==3.10.1
      - numpy==2.2.3
      - pillow==11.1.0
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - six==1.17.0